{% set name = "tesserocr" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77430d272b53dacd3bdd4af5d563fdc24ae51b86fdbc9cf2e8146f29c7abc9a4

build:
  number: 0
  # Skip s390x because of missing leptonica.
  skip: True  # [s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config 0.29.2
  host:
    - tesseract 5.2.0
    - cython 0.29.33
    - setuptools
    - python
    - wheel
    - pip
  run:
    - {{ pin_compatible('tesseract', max_pin='x.x') }}
    - leptonica >=1.7.1 # [not win]
    - pillow
    - python

test:
  imports:
    - tesserocr
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sirfz/tesserocr
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple, Pillow-friendly, Python wrapper around tesseract-ocr API using Cython
  description: |
    tesserocr integrates directly with Tesseract's C++ API using Cython which
    allows for a simple Pythonic and easy-to-read source code. It enables real
    concurrent execution when used with Python's threading module by releasing
    the GIL while processing an image in tesseract.
  doc_url: https://github.com/sirfz/tesserocr
  dev_url: https://github.com/sirfz/tesserocr

extra:
  recipe-maintainers:
    - Chilipp
    - sirfz
